package Exec::Agent::Sandbox;

use strict;
use warnings;
use Carp qw(croak);

# Maps the agent.conf 'sandbox' level onto the systemd filesystem-protection
# directives, and renders the unit drop-in that 'ctrl-exec-agent apply-config'
# installs. agent.conf is the single source of truth; this turns it into the
# ReadWritePaths/ProtectSystem the kernel mount namespace actually enforces.
#
# The drop-in only adjusts filesystem protection (ProtectSystem, ProtectHome,
# ReadWritePaths). Every other hardening directive in the shipped unit
# (NoNewPrivileges, SystemCallFilter, CapabilityBoundingSet, ...) is left intact.

# The drop-in 'ctrl-exec-agent apply-config' writes. A drop-in (rather than an
# edit of the shipped unit) survives package upgrades.
our $DROPIN_DIR  = '/etc/systemd/system/ctrl-exec-agent.service.d';
our $DROPIN_PATH = "$DROPIN_DIR/50-ctrl-exec-sandbox.conf";

# level => filesystem-protection posture.
#   strict   - whole tree read-only except StateDirectory (+ writable_paths).
#   moderate - ProtectSystem=full: /usr, /boot, /etc read-only; /srv, /var,
#              /home, /opt, /mnt writable. Most operational writes just work.
#   off      - no ProtectSystem/ProtectHome: scripts write wherever DAC permits.
my %LEVELS = (
    strict   => { protect_system => 'strict', protect_home => 'yes' },
    moderate => { protect_system => 'full',   protect_home => 'yes' },
    off      => { protect_system => 'no',      protect_home => 'no'  },
);

sub valid_level {
    my ($level) = @_;
    return defined $level && exists $LEVELS{$level} ? 1 : 0;
}

# Render the drop-in text for a parsed agent config. Pure - no I/O - so it is
# unit-tested directly. 'sandbox' defaults to strict; 'writable_paths' is the
# arrayref Config produced (or absent). Dies on an unknown level.
sub render_dropin {
    my ($config) = @_;
    $config //= {};
    my $level = $config->{sandbox} // 'strict';
    croak "invalid sandbox level '$level' (use strict|moderate|off)"
        unless $LEVELS{$level};
    my $spec = $LEVELS{$level};

    my @paths = ref $config->{writable_paths} eq 'ARRAY'
        ? @{ $config->{writable_paths} } : ();

    my $text = <<"HEADER";
# Generated by 'ctrl-exec-agent apply-config' from /etc/ctrl-exec-agent/agent.conf
# Do not edit by hand - re-run apply-config after changing agent.conf.
# sandbox = $level
[Service]
ProtectSystem=$spec->{protect_system}
ProtectHome=$spec->{protect_home}
HEADER

    # Under ProtectSystem=no the whole tree is writable already, so explicit
    # ReadWritePaths are redundant; emit them only when they do something.
    if ($spec->{protect_system} ne 'no') {
        $text .= "ReadWritePaths=$_\n" for @paths;
    }

    return $text;
}

1;
